### ISSUE TITLE
Login Screens

### ISSUE THREAD

**Issue by WillWagnerIV** [WillWagnerIV/The-Coconuts#4]
Menu Functions:
- [x] Splash Screen - Login Menu
- [x] New User Registration Menu
- [ ] User Login Assist Menu
Python DB Functions:
- [x] Add a User to Database - Username and Password only
- [x] Check Username exists
- [x] Verify Matching Password

**Comment by Manarka** [comment]
Like it

**Comment by WillWagnerIV** [comment]
Awesome!
